name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and run Grunt
      run: |
        npm install
        grunt

    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.2
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: 'maven'
          
